stages:
  - build
  - release
  - cleanup

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  BUILD_IMAGE: drmoonlight-web-ui:$CI_BUILD_REF

build:
  stage: build
  script:
    - docker build -t $BUILD_IMAGE .

release:
  stage: release
  script:
    - docker run --rm $BUILD_IMAGE tar cf - ./build | (cd proxy && tar xbf 1 -)
    - cd proxy && docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
    - develop

cleanup:
  stage: cleanup
  script:
    - bash -c "[ -z $(docker images -q $BUILD_IMAGE) ] || docker rmi $BUILD_IMAGE"
  when: always
